//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t ayylmao(float32_t a1);
int32_t levelfive(void);
int32_t levelfour(void);
int32_t levelone(void);
int32_t levelthree(void);
int32_t leveltwo(void);
int32_t magic(int32_t a1);
int32_t rabbit_hole(int32_t a1);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // ebp
struct _IO_FILE * g2 = NULL; // 0x804b060
int32_t g3 = 0; // 0x804b064

// ------------------------ Functions -------------------------

// Address range: 0x804873b - 0x804881f
int32_t levelone(void) {
    int32_t str2 = 0x40772049; // bp-73
    puts("====================================================================");
    puts("                          LEVEL 01                                  ");
    puts("====================================================================");
    printf("Enter code: ");
    int32_t str;
    fgets((char *)&str, 32, g2);
    strcspn((char *)&str, "\n");
    int32_t strcmp_rc = strcmp((char *)&str2, (char *)&str); // 0x80487f5
    if (*(int32_t *)20 != *(int32_t *)20) {
        // 0x8048819
        __stack_chk_fail();
        // branch -> 0x804881e
    }
    // 0x804881e
    return strcmp_rc == 0;
}

// Address range: 0x8048820 - 0x8048918
int32_t leveltwo(void) {
    int32_t v1 = *(int32_t *)20; // bp-16
    puts("====================================================================");
    puts("                          LEVEL 02                                  ");
    puts("====================================================================");
    printf("Enter code: ");
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    scanf("%d %d %d %d %d", &v5, &v4, &v3, &v2, &v1);
    int32_t v6;
    int32_t v7 = (int32_t)&v6 - 32; // 0x80488c5
    int32_t v8 = 7; // 0x80488f62429
    int32_t v9 = 10; // 0x80488f02528
    int32_t v10 = 1; // 0x80488f92627
    // branch -> 0x80488c2
    while (true) {
        int32_t v11 = *(int32_t *)(v7 + 4 * v10); // 0x80488c5
        int32_t v12 = *(int32_t *)(v7 + 4 * (v10 - 1)); // 0x80488cf
        if (v11 == v12 * v8 + v9) {
            int32_t v13 = v10 + 1; // 0x80488e9
            int32_t v14 = v9 ^ v8; // 0x80488f0
            if (v13 >= 5) {
                // break -> 0x8048906
                break;
            }
            v8 = v9;
            v9 = v14;
            v10 = v13;
            // continue -> 0x80488c2
            continue;
        }
        // 0x8048906
        if (*(int32_t *)20 != v1) {
            // 0x8048912
            __stack_chk_fail();
            // branch -> 0x8048917
        }
        // 0x8048917
        return 0;
    }
    // 0x8048906
    if (*(int32_t *)20 != v1) {
        // 0x8048912
        __stack_chk_fail();
        // branch -> 0x8048917
    }
    // 0x8048917
    return 1;
}

// Address range: 0x8048919 - 0x8048968
int32_t magic(int32_t a1) {
    int32_t v1 = 0x1000000 * a1;
    int32_t result = 0;
    if ((v1 || 0xffffff) >= 0x1ffffff) {
        int32_t v2 = v1 / 0x1000000; // 0x01014
        int32_t v3 = v2 % 2; // 0x8048947
        while (v2 >= 2) {
            // 0x8048940
            v2 /= 2;
            v3 += v2 % 2;
            // continue -> 0x8048940
        }
        // 0x804894d
        result = v3;
        // branch -> 0x8048953
    }
    // 0x8048953
    if (*(int32_t *)20 != *(int32_t *)20) {
        // 0x8048962
        __stack_chk_fail();
        // branch -> 0x8048967
    }
    // 0x8048967
    return result;
}

// Address range: 0x8048969 - 0x8048c55
int32_t levelthree(void) {
    int32_t v1 = *(int32_t *)20; // 0x8048970
    puts("====================================================================");
    puts("                          LEVEL 03                                  ");
    puts("====================================================================");
    printf("Enter Code: ");
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int32_t v6;
    scanf("%c %c %c %c %c", &v6, &v5, &v4, &v3, &v2);
    int32_t v7 = magic(0x1000000 * v6 / 0x1000000); // 0x80489e9
    if (v7 != 3) {
        // 0x80489fa
        if (v7 <= 3) {
            // 0x80489ff
            if (v7 == 2) {
                // 0x8048a29
                if (magic(0x1000000 * v5 / 0x1000000) == 1) {
                    goto lab_0x8048a29;
                }
                // 0x8048aa5
                // branch -> 0x8048c43
            }
            // 0x8048c43
            if (*(int32_t *)20 != v1) {
                // 0x8048c4f
                __stack_chk_fail();
                // branch -> 0x8048c54
            }
            // 0x8048c54
            return 0;
        }
        // 0x8048a06
        switch (v7) {
            case 4: {
                // 0x8048b3f
                if (magic(0x1000000 * v5 / 0x1000000) == 2) {
                    goto lab_0x8048b57_2;
                }
                // 0x8048bb7
                // branch -> 0x8048c43
                // 0x8048c43
                if (*(int32_t *)20 != v1) {
                    // 0x8048c4f
                    __stack_chk_fail();
                    // branch -> 0x8048c54
                }
                // 0x8048c54
                return 0;
            }
            case 5: {
                // 0x8048bc8
                if (magic(0x1000000 * v5 / 0x1000000) == 5) {
                    goto lab_0x8048be0_2;
                }
                // 0x8048c3e
                // branch -> 0x8048c43
                // 0x8048c43
                if (*(int32_t *)20 != v1) {
                    // 0x8048c4f
                    __stack_chk_fail();
                    // branch -> 0x8048c54
                }
                // 0x8048c54
                return 0;
            }
        }
        // 0x8048a18
        // branch -> 0x8048c43
        // 0x8048c43
        if (*(int32_t *)20 != v1) {
            // 0x8048c4f
            __stack_chk_fail();
            // branch -> 0x8048c54
        }
        // 0x8048c54
        return 0;
    }
  lab_0x8048ab6_2:
    // 0x8048ab6
    if (magic(0x1000000 * v5 / 0x1000000) != 3 || magic(0x1000000 * v4 / 0x1000000) != 5) {
        // 0x8048b2e
        // branch -> 0x8048c43
        // 0x8048c43
        if (*(int32_t *)20 != v1) {
            // 0x8048c4f
            __stack_chk_fail();
            // branch -> 0x8048c54
        }
        // 0x8048c54
        return 0;
    }
    // 0x8048ae6
    if (magic(0x1000000 * v3 / 0x1000000) != 2) {
        // 0x8048b3f
        if (magic(0x1000000 * v5 / 0x1000000) == 2) {
            goto lab_0x8048b57_2;
        }
        // 0x8048bb7
        // branch -> 0x8048c43
        // 0x8048c43
        if (*(int32_t *)20 != v1) {
            // 0x8048c4f
            __stack_chk_fail();
            // branch -> 0x8048c54
        }
        // 0x8048c54
        return 0;
    }
    // 0x8048afe
    if (magic(0x1000000 * v2 / 0x1000000) != 2 || magic(0x1000000 * v5 / 0x1000000) != 1) {
        // 0x8048b1a
        // branch -> 0x8048c43
        // 0x8048c43
        if (*(int32_t *)20 != v1) {
            // 0x8048c4f
            __stack_chk_fail();
            // branch -> 0x8048c54
        }
        // 0x8048c54
        return 0;
    }
  lab_0x8048a29:
    // 0x8048a41
    if (magic(0x1000000 * v4 / 0x1000000) != 3) {
        // 0x8048bc8
        if (magic(0x1000000 * v5 / 0x1000000) == 5) {
            goto lab_0x8048be0_2;
        }
        // 0x8048c3e
        // branch -> 0x8048c43
        // 0x8048c43
        if (*(int32_t *)20 != v1) {
            // 0x8048c4f
            __stack_chk_fail();
            // branch -> 0x8048c54
        }
        // 0x8048c54
        return 0;
    }
    // 0x8048a5d
    if (magic(0x1000000 * v3 / 0x1000000) != 2) {
        // 0x8048a9b
        // branch -> 0x8048c43
        // 0x8048c43
        if (*(int32_t *)20 != v1) {
            // 0x8048c4f
            __stack_chk_fail();
            // branch -> 0x8048c54
        }
        // 0x8048c54
        return 0;
    }
    // 0x8048a75
    if (magic(0x1000000 * v2 / 0x1000000) == 4) {
        // 0x8048a91
        // branch -> 0x8048c43
        // 0x8048c43
        if (*(int32_t *)20 != v1) {
            // 0x8048c4f
            __stack_chk_fail();
            // branch -> 0x8048c54
        }
        // 0x8048c54
        return 1;
    }
    // 0x8048b3f
    if (magic(0x1000000 * v5 / 0x1000000) != 2) {
        // 0x8048bb7
        // branch -> 0x8048c43
        // 0x8048c43
        if (*(int32_t *)20 != v1) {
            // 0x8048c4f
            __stack_chk_fail();
            // branch -> 0x8048c54
        }
        // 0x8048c54
        return 0;
    }
  lab_0x8048b57_2:
    // 0x8048b57
    if (magic(0x1000000 * v4 / 0x1000000) != 1) {
        goto lab_0x8048ab6_2;
    }
    // 0x8048b73
    if (magic(0x1000000 * v3 / 0x1000000) != 5 || magic(0x1000000 * v2 / 0x1000000) == 1 || magic(0x1000000 * v5 / 0x1000000) != 5) {
        // 0x8048bad
        // branch -> 0x8048c43
        // 0x8048c43
        if (*(int32_t *)20 != v1) {
            // 0x8048c4f
            __stack_chk_fail();
            // branch -> 0x8048c54
        }
        // 0x8048c54
        return 0;
    }
  lab_0x8048be0_2:
    // 0x8048be0
    if (magic(0x1000000 * v4 / 0x1000000) != 3) {
        goto lab_0x8048a29;
    }
    // 0x8048bfc
    if (magic(0x1000000 * v3 / 0x1000000) == 5) {
        // 0x8048c14
        if (magic(0x1000000 * v2 / 0x1000000) == 4) {
            goto lab_0x8048ab6_2;
        }
        // 0x8048c30
        // branch -> 0x8048c43
    }
    // 0x8048c43
    if (*(int32_t *)20 != v1) {
        // 0x8048c4f
        __stack_chk_fail();
        // branch -> 0x8048c54
    }
    // 0x8048c54
    return 0;
}

// Address range: 0x8048c56 - 0x8048cb8
int32_t rabbit_hole(int32_t a1) {
    int32_t result = 1;
    if (a1 > 0) {
        int32_t v1 = rabbit_hole(a1 - 2); // 0x8048c85
        result = rabbit_hole(a1 - 4) + v1;
        // branch -> 0x8048ca3
    }
    // 0x8048ca3
    if (*(int32_t *)20 != *(int32_t *)20) {
        // 0x8048caf
        __stack_chk_fail();
        // branch -> 0x8048cb4
    }
    // 0x8048cb4
    return result;
}

// Address range: 0x8048cb9 - 0x8048d55
int32_t levelfour(void) {
    puts("====================================================================");
    puts("                          LEVEL 04                                  ");
    puts("====================================================================");
    printf("Enter Code: ");
    int32_t v1;
    scanf("%d", &v1);
    int32_t result = rabbit_hole(v1 / 8) == 0x3c50ea2;
    if (*(int32_t *)20 != *(int32_t *)20) {
        // 0x8048d4f
        __stack_chk_fail();
        // branch -> 0x8048d54
    }
    // 0x8048d54
    return result;
}

// Address range: 0x8048d56 - 0x8048dda
int32_t ayylmao(float32_t a1) {
    // 0x8048d56
    if (*(int32_t *)20 != *(int32_t *)20) {
        // 0x8048dd2
        __stack_chk_fail();
        // branch -> 0x8048dd9
    }
    // 0x8048dd9
    int32_t v1;
    g1 = v1;
    return 0x5f3759df - (int32_t)a1 / 2;
}

// Address range: 0x8048ddb - 0x8048f01
int32_t levelfive(void) {
    int32_t v1 = *(int32_t *)20; // 0x8048de2
    int32_t v2 = 3; // bp-56
    puts("====================================================================");
    puts("                          LEVEL 05                                  ");
    puts("====================================================================");
    printf("Enter Code: ");
    // branch -> 0x8048e58
    for (int32_t i = 0; i < 5; i++) {
        // 0x8048e58
        scanf("%f", (float64_t *)((int32_t)&v2 + 4 + 8 * i));
        // continue -> 0x8048e58
    }
    // 0x8048ee4
    int32_t v3;
    int32_t v4 = &v3; // 0x8048e8d
    int32_t v5 = 0;
    // branch -> 0x8048e8a
    while (true) {
        int32_t v6 = 8 * v5; // 0x8048e8d
        ayylmao(*(float32_t *)(v4 - 48 + v6));
        float64_t v7 = round(0.0); // 0x8048ead
        int32_t v8 = g1; // 0x8048ed1
        int32_t v9 = *(int32_t *)(v6 - 52 + v8); // 0x8048ed1
        int32_t v10 = v5 + 1; // 0x8048ee0
        if ((int32_t)v7 == v9) {
            // 0x8048ee4
            if (v10 >= 5) {
                // break -> 0x8048eef
                break;
            }
            v4 = v8;
            v5 = v10;
            // continue -> 0x8048e8a
            continue;
        }
        // 0x8048eef
        if (*(int32_t *)20 != v1) {
            // 0x8048efb
            __stack_chk_fail();
            // branch -> 0x8048f00
        }
        // 0x8048f00
        return 0;
    }
    // 0x8048eef
    if (*(int32_t *)20 != v1) {
        // 0x8048efb
        __stack_chk_fail();
        // branch -> 0x8048f00
    }
    // 0x8048f00
    return 1;
}

// Address range: 0x8048f02 - 0x80490ef
int main(int argc, char ** argv) {
    // 0x8048f02
    if (ptrace(0) == -1) {
        // 0x8048f33
        exit(0);
        // UNREACHABLE
    }
    // 0x8048f3d
    setvbuf(g2, NULL, 2, 0);
    setvbuf((struct _IO_FILE *)g3, NULL, 2, 0);
    puts("                                 Welcome to                                    ");
    puts(" ______     __  __     __  __        ______   __     __         __         ______     ______");
    puts("/\\  ___\\   /\\ \\/ /    /\\ \\_\\ \\      /\\  == \\ /\\ \\   /\\ \\       /\\ \\       /\\  __ \\   /\\  == \\");
    puts("\\ \\___  \\  \\ \\  _\"-.  \\ \\____ \\     \\ \\  _-/ \\ \\ \\  \\ \\ \\____  \\ \\ \\____  \\ \\  __ \\  \\ \\  __<");
    puts(" \\/\\_____\\  \\ \\_\\ \\_\\  \\/\\_____\\     \\ \\_\\    \\ \\_\\  \\ \\_____\\  \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_\\ \\_\\");
    puts("  \\/_____/   \\/_/\\/_/   \\/_____/      \\/_/     \\/_/   \\/_____/   \\/_____/   \\/_/\\/_/   \\/_/ /_/");
    puts("================================================================================");
    puts("                    Home of the legendary Pokemon, Rayquaza                          ");
    puts("================================================================================");
    puts("There are 5 Levels to climb. Each level requires a specifc code to unlock the next level.");
    puts("Your goal is to reach the top, and catch the legendary Rayquaza... Good luck!");
    if (levelone() == 0) {
        // 0x8049039
        exit(0);
        // UNREACHABLE
    }
    // 0x804901e
    puts("CrossCTF{xxxxxxxxxxxxxxxxx}");
    if (leveltwo() == 0) {
        // 0x804905e
        exit(0);
        // UNREACHABLE
    }
    // 0x8049043
    puts("CrossCTF{xxxxxxxxxxxxxxxxx}");
    if (levelthree() == 0) {
        // 0x8049083
        exit(0);
        // UNREACHABLE
    }
    // 0x8049068
    puts("CrossCTF{xxxxxxxxxxxxxxxxx}");
    if (levelfour() == 0) {
        // 0x80490a8
        exit(0);
        // UNREACHABLE
    }
    // 0x804908d
    puts("CrossCTF{xxxxxxxxxxxxxxxxx}");
    if (levelfive() == 0) {
        // 0x80490d5
        exit(0);
        // UNREACHABLE
    }
    // 0x80490b2
    puts("CrossCTF{xxxxxxxxxxxxxxxxx}");
    if (*(int32_t *)20 != *(int32_t *)20) {
        // 0x80490df
        __stack_chk_fail();
        // branch -> 0x80490e4
    }
    // 0x80490e4
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// void __stack_chk_fail(void);
// void exit(int status);
// char * fgets(char * restrict s, int n, FILE * restrict stream);
// int printf(const char * restrict format, ...);
// long int ptrace(enum __ptracerequest __request, ...);
// int puts(const char * s);
// double round(double);
// int scanf(const char * restrict format, ...);
// int setvbuf(FILE * restrict stream, char * restrict buf, int modes, size_t n);
// int strcmp(const char * s1, const char * s2);
// size_t strcspn(const char * s, const char * reject);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 9
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-06-17 07:52:13
