//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t transcheck(char * str, char * str2);

// --------------------- Global Variables ---------------------

char ** g1 = NULL; // 0x804a034

// ------------------------ Functions -------------------------

// Address range: 0x804858e - 0x80486dd
int32_t transcheck(char * str, char * str2) {
    int32_t v1 = 0; // ecx
    int32_t len = strlen(str); // 0x8048598
    int32_t result = 0;
    if (len == strlen(str2)) {
        int32_t mem = (int32_t)calloc(26, 4); // 0x80485bf_5
        int32_t mem2 = (int32_t)calloc(26, 4); // 0x80485ce_5
        char v2 = *str; // 0x804868946
        int32_t v3 = 0;
        int32_t v4; // 0x80486cb
        int32_t v5; // 0x80486c1
        int32_t v6; // 0x80486a4
        int32_t v7;
        if (v2 != 0) {
            int32_t v8 = (int32_t)str;
            // branch -> 0x80485ea
            while (true) {
                int32_t v9 = v2; // 0x80485ed
                int32_t v10 = (int32_t)v2 % 0x10000 | v1 & -0x10000; // 0x80485f0
                v1 = 26;
                int32_t * v11 = (int32_t *)(0x1000000 * (v9 + -26 * ((0x4f0000 * v10 / 0x8000000 % 256 | 79 * v10 & -0x10000) - (0x1000000 * v9 >> 31) % 256)) / 0x400000 + mem); // 0x804862d_0
                *v11 = *v11 + 1;
                unsigned char v12 = *str2; // 0x8048637
                int32_t v13 = v12; // 0x8048637
                int32_t v14 = (int32_t)v12 % 0x10000 | v1 & -0x10000; // 0x804863a
                int32_t * v15 = (int32_t *)(0x1000000 * (v13 + -26 * ((0x4f0000 * v14 / 0x8000000 % 256 | 79 * v14 & -0x10000) - (0x1000000 * v13 >> 31) % 256)) / 0x400000 + mem2); // 0x8048677_0
                *v15 = *v15 + 1;
                int32_t v16 = v8 + 1; // 0x804867e
                char v17 = *(char *)v16; // 0x8048689
                if (v17 == 0) {
                    v3 = 0;
                    // break -> 0x80486a1
                    break;
                }
                v2 = v17;
                v8 = v16;
                str2 = (char *)((int32_t)str2 + 1);
                // continue -> 0x80485ea
            }
            v6 = 4 * v3;
            v5 = *(int32_t *)(v6 + mem2);
            v7 = *(int32_t *)(v6 + mem) == v5 ? 1 : 0;
            v4 = v3 + 1;
            while (v4 < 26) {
                // 0x80486a1
                v3 = v4;
                v6 = 4 * v3;
                v5 = *(int32_t *)(v6 + mem2);
                v7 = *(int32_t *)(v6 + mem) == v5 ? v7 : 0;
                v4 = v3 + 1;
                // continue -> 0x80486a1
            }
            // 0x80486d5
            // branch -> 0x80486d9
            // 0x80486d9
            return v7 % 256;
        }
        v6 = 4 * v3;
        v5 = *(int32_t *)(v6 + mem2);
        v7 = *(int32_t *)(v6 + mem) == v5 ? 1 : 0;
        v4 = v3 + 1;
        while (v4 < 26) {
            // 0x80486a1
            v3 = v4;
            v6 = 4 * v3;
            v5 = *(int32_t *)(v6 + mem2);
            v7 = *(int32_t *)(v6 + mem) == v5 ? v7 : 0;
            v4 = v3 + 1;
            // continue -> 0x80486a1
        }
        // 0x80486d5
        result = v7 % 256;
        // branch -> 0x80486d9
    }
    // 0x80486d9
    return result;
}

// Address range: 0x80486de - 0x804884f
int main(int argc, char ** argv) {
    puts(" _____                      __                                     ");
    puts("/__   \\_ __ __ _ _ __  ___ / _| ___  _ __ _ __ ___   ___ _ __     ");
    puts("  / /\\/ '__/ _` | '_ \\/ __| |_ / _ \\| '__| '_ ` _ \\ / _ \\ '__|");
    puts(" / /  | | | (_| | | | \\__ \\  _| (_) | |  | | | | | |  __/ |      ");
    puts(" \\/   |_|  \\__,_|_| |_|___/_|  \\___/|_|  |_| |_| |_|\\___|_|    ");
    puts("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    puts("        ~ Anagram Checker w/o any Steganography bullshit ~         ");
    puts("             (Too bad this isn't worth 2999 points)                ");
    puts("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    fflush((struct _IO_FILE *)g1);
    printf("Word #1: ");
    fflush((struct _IO_FILE *)g1);
    int32_t v1;
    scanf("%s", &v1);
    printf("Word #2: ");
    fflush((struct _IO_FILE *)g1);
    int32_t v2;
    scanf("%s", &v2);
    fflush((struct _IO_FILE *)g1);
    if (transcheck((char *)&v1, (char *)&v2) == 0) {
        // 0x804881b
        printf("%s and %s are not anagrams\n", &v1, &v2);
        fflush((struct _IO_FILE *)g1);
        // branch -> 0x8048844
    } else {
        // 0x80487f0
        printf("%s and %s are anagrams\n", &v1, &v2);
        fflush((struct _IO_FILE *)g1);
        // branch -> 0x8048844
    }
    // 0x8048844
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// void * calloc(size_t nmemb, size_t size);
// int fflush(FILE * stream);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// int scanf(const char * restrict format, ...);
// size_t strlen(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 2
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-06-17 07:30:17
